### ISSUE TITLE
Cannot find module './node_modules/platform'

### ISSUE THREAD

**Issue by tocacyy** [lucasveneno/trafficbot#2]
Hi
How can I resolve this error. Thx

Error: Cannot find module './node_modules/platform'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/trafficbot/index.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by lucasveneno** [comment]
The module was added if you need a new module just install with npm

https://www.npmjs.com/package/platform

To install a new module just go to the main folder of the project "/trafficbot" and install with:

`$ npm i platform`

> You'll need to get node installed on your computer
