### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by xslyl** [lucasveneno/trafficbot#5]
Now checking 0
OS: Windows Server 2008 R2 / 7
Proxy:  127.0.0.1:5566
Browser:  opera
Url:  https://iphub.info/
Width:  640
Height:  480
Miliseconds per page: 20000
Layout: Blink
#0
Error: { Error: navigation error
    at unserializeError (/root/trafficbot/node_modules/nightmare/lib/ipc.js:162:13)
    at EventEmitter.<anonymous> (/root/trafficbot/node_modules/nightmare/lib/ipc.js:89:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at ChildProcess.<anonymous> (/root/trafficbot/node_modules/nightmare/lib/ipc.js:49:10)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
  code: -130,
  details: 'ERR_PROXY_CONNECTION_FAILED',
  url: 'https://iphub.info/' }
undefined

**Comment by lucasveneno** [comment]
There is something wrong with the proxy server, it looks like your proxy "127.0.0.1:5566" is not working or there is no internet connection. trying test without use proxies

```
ERROR DETAILS:
code: -130,
details: 'ERR_PROXY_CONNECTION_FAILED',
url: 'https://iphub.info/' 
```

**Comment by lucasveneno** [comment]
There is something wrong with the proxy server, it looks like your proxy "127.0.0.1:5566" is not working or there is no internet connection. please trynna without proxies or check if the port is open

ERROR DETAILS:
code: -130,
details: 'ERR_PROXY_CONNECTION_FAILED',
url: 'https://iphub.info/'

**Comment by lucasveneno** [comment]
There is something wrong with the proxy server, it looks like your proxy "127.0.0.1:5566" is not working or there is no internet connection. Please trynna use without proxies or check if the port is open.

ERROR DETAILS:
code: -130,
details: 'ERR_PROXY_CONNECTION_FAILED',
url: 'https://iphub.info/'

**Comment by lucasveneno** [comment]
There is something wrong with the proxy server, it looks like your proxy "127.0.0.1:5566" is not working or there is no internet connection. Please trynna use without proxies or check if the port is open.

ERROR DETAILS:
```
code: -130,
details: 'ERR_PROXY_CONNECTION_FAILED',
url: 'https://iphub.info/'
```

**Comment by xslyl** [comment]
No proxy mode is operating normally
There is a new problem
Error: { TypeError: Cannot read property 'href' of undefined
    at fn (<anonymous>:20:105)
    at javascript (<anonymous>:35:21)
    at <anonymous>:50:3
    at EventEmitter.electron.ipcRenderer.on (/root/trafficbot/node_modules/electron/dist/resources/electron.asar/renderer/web-frame-init.js:36:30)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7) code: -1 }
undefined

**Comment by lucasveneno** [comment]
The script look for source code of the page and get "href" properties from <a> tags, but this is returning undefined, maybe a condition will solve this, I've gotta do some tests later... Thanks mate!
